//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anexo_de_Vehiculos
    {
        public string Placa { get; set; }
        public string Volumen { get; set; }
        public string Tipo_Traccion { get; set; }
        public Nullable<short> Tipo_Carroceria { get; set; }
    }
}
