//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Hertz
    {
        public string Rut { get; set; }
        public string Patente { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento { get; set; }
        public string Nro_factura { get; set; }
        public Nullable<System.DateTime> Fecha_Factura { get; set; }
        public Nullable<System.DateTime> Fecha_Factura_homologacion { get; set; }
        public Nullable<decimal> Valor_neto_factura { get; set; }
        public string Digito_verificador_patente { get; set; }
        public string Codigo_sii { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<decimal> Tasacion { get; set; }
        public string Motor { get; set; }
        public string Chasis { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Nro_asientos { get; set; }
        public Nullable<decimal> Tara { get; set; }
        public string Nombre_Propietario { get; set; }
        public string Domicilio_Propietario { get; set; }
        public string Comuna_Propietario { get; set; }
        public string Telefono_Propietario { get; set; }
        public string Celular_Propietario { get; set; }
        public string Correo_Propietario { get; set; }
        public string Sello_verde { get; set; }
        public Nullable<System.DateTime> Fecha_Plazo_homologacion { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Tipo_vehiculo { get; set; }
        public Nullable<int> Cilindrada { get; set; }
        public string Combustible { get; set; }
        public string Transmision { get; set; }
        public string Equipamiento { get; set; }
        public Nullable<int> Nro_Puertas { get; set; }
        public string Zona_Franca { get; set; }
        public Nullable<decimal> Tonelaje { get; set; }
        public string Personalizado_1 { get; set; }
        public decimal Correlativo { get; set; }
    }
}
