//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boletines_en_Tarjetas
    {
        public decimal Codigo { get; set; }
        public double Boletin { get; set; }
        public string Observacion { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public string placa { get; set; }
        public string rut { get; set; }
        public string Caja { get; set; }
        public string Usuario { get; set; }
        public short Tipo_de_Ingreso { get; set; }
    }
}
