//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Boletines_Nulos
    {
        public double Numero_Boletin { get; set; }
        public System.DateTime Fecha { get; set; }
        public short Numero_Caja { get; set; }
        public string Observacion { get; set; }
        public Nullable<float> Numero_Boletin_Preimpreso { get; set; }
    }
}
