//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cajas
    {
        public short Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> Desde_Boletin { get; set; }
        public Nullable<long> Hasta_Boletin { get; set; }
        public Nullable<int> Codigo_Ubicacion { get; set; }
    }
}
