//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cambio_Dueño
    {
        public long ID { get; set; }
        public string Placa { get; set; }
        public string Fecha_de_Cambio { get; set; }
        public string Observacion { get; set; }
        public string Tipo_Vehiculo_Anterior { get; set; }
    }
}
