//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carros_Remolques_Factura_Declaracion
    {
        public string Placa { get; set; }
        public string Digito { get; set; }
        public short Declaracion_Jurada { get; set; }
        public Nullable<long> Numero_Factura { get; set; }
        public Nullable<System.DateTime> Fecha_Factura { get; set; }
        public Nullable<int> Neto_Factura { get; set; }
        public string Rut_Factura { get; set; }
        public string Nombre_Notario { get; set; }
    }
}
