//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobantes_Pago_Multas
    {
        public int ID { get; set; }
        public string Id_Multa { get; set; }
        public string Placa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Ruta { get; set; }
    }
}
