//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunas
    {
        public short Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Informacion_Comuna { get; set; }
        public Nullable<int> Region { get; set; }
        public string Codigo_Nacional { get; set; }
        public string RUT_COMUNA { get; set; }
    }
}
