//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_Pago_Deuda
    {
        public double Folio { get; set; }
        public string ID_JPL { get; set; }
        public string Placa { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public string Usuar_Name { get; set; }
        public string Observaciones { get; set; }
    }
}
