//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_Vencimiento_CHI
    {
        public int ID { get; set; }
        public short Año_Emision { get; set; }
        public short Mes_Emision { get; set; }
        public string Digito_Placa { get; set; }
        public short Año_Vencimiento { get; set; }
        public short Mes_Vencimiento { get; set; }
        public System.DateTime Fecha_Validez { get; set; }
    }
}
