//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crea_Correlativo_Varios
    {
        public short TIPO { get; set; }
        public short ANO_PROCESO { get; set; }
        public int FOLIO { get; set; }
        public short TIPO_FOLIO { get; set; }
    }
}
