//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas_por_Periodo
    {
        public short Periodo { get; set; }
        public short Id { get; set; }
        public string Descripcion { get; set; }
        public string Cuenta_Contable { get; set; }
        public Nullable<short> Item_Tesoreria { get; set; }
    }
}
