//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_Incorporacion
    {
        public string Placa { get; set; }
        public System.DateTime Fecha { get; set; }
        public short Comuna_Origen { get; set; }
        public string Observaciones { get; set; }
        public string Mail_Municipo { get; set; }
    }
}
