//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_Historico_CarrosRemolques
    {
        public string Placa { get; set; }
        public System.DateTime Fecha { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> N_Folio_Tarjeta { get; set; }
    }
}
