//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_del_Vehiculo
    {
        public string Placa { get; set; }
        public string Digito { get; set; }
        public string Rut { get; set; }
        public Nullable<int> Tipo_Vehiculo { get; set; }
        public Nullable<short> Clasificacion { get; set; }
        public string Codigo_SII { get; set; }
        public Nullable<short> Codigo_Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<short> Año_Fabricacion { get; set; }
        public string Color { get; set; }
        public string Numero_Motor { get; set; }
        public string Numero_Chassis { get; set; }
        public Nullable<short> Numero_Puertas { get; set; }
        public Nullable<int> Tonelaje { get; set; }
        public Nullable<short> Numero_Asientos { get; set; }
        public Nullable<short> Numero_Ejes { get; set; }
        public Nullable<short> Numero_Ruedas { get; set; }
        public int Tipo_Sello { get; set; }
        public string Numero_Sello { get; set; }
        public Nullable<int> Compañia_Seguro { get; set; }
        public string Numero_Poliza { get; set; }
        public string Nro_Revision_Tecnica { get; set; }
        public string Lugar_Revision_Tecnica { get; set; }
        public string Folio_Gases { get; set; }
        public Nullable<bool> Trasladado { get; set; }
        public Nullable<System.DateTime> Fecha_Traslado { get; set; }
        public Nullable<short> Comuna_Traslado { get; set; }
        public bool Usar_para_envio_de_Correo { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Comuna { get; set; }
        public string Telefono { get; set; }
        public string Codigo_Postal { get; set; }
        public bool Asimilado { get; set; }
        public bool Tasado { get; set; }
        public Nullable<int> Tasacion { get; set; }
        public Nullable<int> Neto_Factura { get; set; }
        public Nullable<System.DateTime> Fecha_Factura { get; set; }
        public Nullable<long> Numero_Factura { get; set; }
        public Nullable<short> Cilindrada { get; set; }
        public string Combustible { get; set; }
        public string Equipamiento { get; set; }
        public string Transmision { get; set; }
        public string Observaciones { get; set; }
        public Nullable<short> Estado_Vehiculo { get; set; }
        public string Rut_Factura { get; set; }
        public string Nombre_Notario { get; set; }
        public Nullable<short> Declaracion_Jurada { get; set; }
        public Nullable<System.DateTime> Fecha_VencRevTec { get; set; }
        public Nullable<short> Tipo_RevTec { get; set; }
        public Nullable<System.DateTime> Fecha_Aprueba_Traslado { get; set; }
        public Nullable<short> Codigo_ZonaFranca { get; set; }
        public string Numero_VIN { get; set; }
        public Nullable<int> Año_Anterior { get; set; }
        public Nullable<double> Boletin_Anterior { get; set; }
        public Nullable<int> Comunidad_Int { get; set; }
        public string Kardex { get; set; }
        public Nullable<decimal> Vfactura_Original { get; set; }
        public Nullable<System.DateTime> Fecha_Termino_Seguro { get; set; }
        public Nullable<int> Importado_Excel { get; set; }
        public string Numero_Chasis { get; set; }
        public string Potencia { get; set; }
        public string Marchas { get; set; }
        public string Traccion { get; set; }
        public string Equipamiento_Detallado { get; set; }
        public Nullable<double> Permiso_Año { get; set; }
        public string Version { get; set; }
        public string RUT_X { get; set; }
        public string hash { get; set; }
    }
}
