//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_del_CarrosRemolques
    {
        public string Placa { get; set; }
        public string Digito { get; set; }
        public string Rut { get; set; }
        public Nullable<short> Tipo_Vehiculo { get; set; }
        public Nullable<short> Codigo_Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<short> Ano_Fabricacion { get; set; }
        public string Color { get; set; }
        public Nullable<int> Tonelaje { get; set; }
        public Nullable<short> Numero_Ejes { get; set; }
        public Nullable<short> Numero_Ruedas { get; set; }
        public Nullable<System.DateTime> Fecha_incripcion { get; set; }
        public Nullable<double> Numero_registro { get; set; }
        public Nullable<double> Numero_folio { get; set; }
        public Nullable<int> Emitido { get; set; }
        public Nullable<System.DateTime> FechaEmitido { get; set; }
    }
}
