//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Derechos_Varios
    {
        public int Numero_Orden { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Placa { get; set; }
        public string Digito { get; set; }
        public string Rut { get; set; }
        public string Contribuyente { get; set; }
        public string Direccion { get; set; }
        public string Comuna { get; set; }
        public string Glosa { get; set; }
        public short Estado { get; set; }
        public Nullable<int> Caja_Transito { get; set; }
        public Nullable<int> Caja_Tesoreria { get; set; }
        public string Glosa2 { get; set; }
        public string Glosa3 { get; set; }
        public Nullable<double> Id_Multa { get; set; }
        public int Ano_Proceso { get; set; }
    }
}
