//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class DerVar
    {
        public int Id { get; set; }
        public string Placa { get; set; }
        public Nullable<short> Forma_de_Pago { get; set; }
        public Nullable<short> Año_del_Permiso { get; set; }
        public Nullable<double> Numero_Boletin { get; set; }
        public Nullable<System.DateTime> Fecha_Emision { get; set; }
        public Nullable<int> Valor_Duplicado { get; set; }
        public Nullable<short> Numero_Caja { get; set; }
        public Nullable<byte> Estado_del_Pago { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
        public string Usuario { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Correlativo_Caja { get; set; }
        public string Usuario_Caja { get; set; }
        public Nullable<short> Año_Proceso { get; set; }
        public Nullable<int> Tipo { get; set; }
    }
}
