//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleNominas
    {
        public int IdDetalle { get; set; }
        public Nullable<int> IdNomina { get; set; }
        public Nullable<int> IdSubdere { get; set; }
    
        public virtual Nominas Nominas { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
