//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Derechos_Varios
    {
        public int Numero_Orden { get; set; }
        public short Codigo { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<short> Item_Tesoreria { get; set; }
        public Nullable<int> Ano_Proceso { get; set; }
    }
}
