//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eliminacion_por_Decreto
    {
        public string Placa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Numero_Decreto { get; set; }
        public string Observaciones { get; set; }
    }
}
