//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int Codigo_Empresa { get; set; }
        public string Descripcion_Empresa { get; set; }
        public string Rut { get; set; }
        public string Direccion { get; set; }
        public string Representante_Legal { get; set; }
    }
}
