//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQU_COMUNAS_CONSORCIO
    {
        public int ID { get; set; }
        public short COD_COMUN_CONSORCIO { get; set; }
        public short COD_COMUN { get; set; }
        public string NOMBRE_COMUNA { get; set; }
        public string NOMBRE_CONSORCIO { get; set; }
    }
}
