//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha_Vehiculo
    {
        public string Placa { get; set; }
        public string Digito { get; set; }
        public string TipoVehiculo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<short> Año_Fabricacion { get; set; }
        public string Color { get; set; }
        public Nullable<byte> Numero_Puertas { get; set; }
        public string Numero_Motor { get; set; }
        public string Numero_Chassis { get; set; }
        public Nullable<int> Tonelaje { get; set; }
        public Nullable<byte> Numero_Asientos { get; set; }
        public bool Tasado { get; set; }
        public Nullable<int> Tasacion { get; set; }
        public string Clasificacion { get; set; }
        public Nullable<double> TasacionSII { get; set; }
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Comuna { get; set; }
        public Nullable<short> Año_del_Permiso { get; set; }
        public Nullable<double> Numero_Boletin { get; set; }
        public Nullable<System.DateTime> Fecha_Emision { get; set; }
        public Nullable<byte> Forma_de_Pago { get; set; }
        public Nullable<int> Total_a_Pagar { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento { get; set; }
    }
}
