//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Generacion_Preemision
    {
        public int Año_del_Permiso { get; set; }
        public short Tipo { get; set; }
        public double Numero_Boletin { get; set; }
        public string Placa { get; set; }
        public string Nombre_Propietario { get; set; }
        public string Rut_Propietario { get; set; }
        public string Direccion { get; set; }
        public string Comuna { get; set; }
        public string Telefono { get; set; }
        public string Tipo_Vehiculo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<short> Año_Fabricacion { get; set; }
        public Nullable<short> Nro_Puertas { get; set; }
        public Nullable<short> Nro_Asientos { get; set; }
        public Nullable<int> Tonelaje { get; set; }
        public string Nro_Chassis { get; set; }
        public string Nro_Motor { get; set; }
        public string Color { get; set; }
        public string Codigo_SII { get; set; }
        public Nullable<int> Tasacion { get; set; }
        public Nullable<double> Valor_Cuota { get; set; }
        public Nullable<double> Valor_Contado { get; set; }
        public string Glosa_Tipo_Pago { get; set; }
        public Nullable<short> Cilindrada { get; set; }
        public string Combustible { get; set; }
        public string Transmision { get; set; }
        public string Equipamiento { get; set; }
        public string Glosa_Sello_Verde { get; set; }
        public string Glosa_General { get; set; }
        public string Glosa_en_Permiso { get; set; }
        public Nullable<double> IPC_2da_Cuota { get; set; }
        public Nullable<double> Total_2da_Cuota { get; set; }
        public string Clasificacion { get; set; }
        public Nullable<double> Valor_UTM { get; set; }
        public Nullable<short> Comuna_Anterior { get; set; }
        public Nullable<short> Ano_Anterior { get; set; }
        public Nullable<double> Correccion_Monetaria { get; set; }
        public Nullable<int> Monto_Correccion { get; set; }
    }
}
