//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico_Reemplazo_Placas
    {
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fecha_Cambio { get; set; }
        public string Placa_Antigua { get; set; }
        public string Digito_PlacaA { get; set; }
        public string Placa_Nueva { get; set; }
        public string Digito_PlacaN { get; set; }
    }
}
