//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hist_Rev_Tecnicas_Seguros
    {
        public string Placa { get; set; }
        public Nullable<System.DateTime> Fecha_VencRevTec { get; set; }
        public Nullable<double> Nro_Poliza { get; set; }
        public Nullable<int> Cia_Seguro { get; set; }
        public string Nro_Rev_Tec { get; set; }
        public string Lugar { get; set; }
        public string Folio_Gases { get; set; }
        public Nullable<short> Tipo { get; set; }
        public Nullable<System.DateTime> Fecha_Termino_Seguro { get; set; }
        public Nullable<System.DateTime> Fecha_Emision_CHI { get; set; }
        public Nullable<int> Tipo_De_Ingreso { get; set; }
    }
}
