//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impuesto
    {
        public short Tramo { get; set; }
        public Nullable<double> Desde { get; set; }
        public Nullable<double> Hasta { get; set; }
        public Nullable<decimal> Impuesto1 { get; set; }
        public Nullable<decimal> Rebaja { get; set; }
    }
}
