//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indices
    {
        public short Año { get; set; }
        public short Mes { get; set; }
        public Nullable<double> Valor_UTM { get; set; }
        public Nullable<double> IPC_Acumulado { get; set; }
    }
}
