//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe_Dinamico_QR
    {
        public int ID { get; set; }
        public Nullable<int> Seccion { get; set; }
        public Nullable<int> Alto { get; set; }
        public Nullable<int> Ancho { get; set; }
        public Nullable<int> Posicion_X { get; set; }
        public Nullable<int> Posicion_Y { get; set; }
    }
}
