//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lugares
    {
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public double Correlativo { get; set; }
        public Nullable<double> Correlativo_Desde { get; set; }
        public Nullable<double> Correlativo_Hasta { get; set; }
    }
}
