//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Permisos_de_CirculacionEntities : DbContext
    {
        public Permisos_de_CirculacionEntities()
            : base("name=Permisos_de_CirculacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Derechos_Varios> Derechos_Varios { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Encuesta_Anual> Encuesta_Anual { get; set; }
        public virtual DbSet<Factura_Internet> Factura_Internet { get; set; }
        public virtual DbSet<Notificacion_Actualizacion_Estructura> Notificacion_Actualizacion_Estructura { get; set; }
        public virtual DbSet<Regiones> Regiones { get; set; }
        public virtual DbSet<Series_Placas> Series_Placas { get; set; }
        public virtual DbSet<Traslados_de_Vehiculos> Traslados_de_Vehiculos { get; set; }
        public virtual DbSet<C_Bloqueo_de_Vehiculos> C_Bloqueo_de_Vehiculos { get; set; }
        public virtual DbSet<C_Boletines_Nulos> C_Boletines_Nulos { get; set; }
        public virtual DbSet<C_Cajas> C_Cajas { get; set; }
        public virtual DbSet<C_Codigos_ComunaJPL_SRCEI> C_Codigos_ComunaJPL_SRCEI { get; set; }
        public virtual DbSet<C_Codigos_JPL_SRCEI> C_Codigos_JPL_SRCEI { get; set; }
        public virtual DbSet<C_Compañias_de_Seguros> C_Compañias_de_Seguros { get; set; }
        public virtual DbSet<C_Historico_Tasaciones_> C_Historico_Tasaciones_ { get; set; }
        public virtual DbSet<Anexo_de_Vehiculos> Anexo_de_Vehiculos { get; set; }
        public virtual DbSet<Asignacion_de_Cuentas> Asignacion_de_Cuentas { get; set; }
        public virtual DbSet<Autorizacion_Usuarios> Autorizacion_Usuarios { get; set; }
        public virtual DbSet<Base_Hertz> Base_Hertz { get; set; }
        public virtual DbSet<Bloque_de_Personas> Bloque_de_Personas { get; set; }
        public virtual DbSet<Bloqueo_de_Vehiculos> Bloqueo_de_Vehiculos { get; set; }
        public virtual DbSet<Boletines_en_Tarjetas> Boletines_en_Tarjetas { get; set; }
        public virtual DbSet<Boletines_Nulos> Boletines_Nulos { get; set; }
        public virtual DbSet<Cajas> Cajas { get; set; }
        public virtual DbSet<Cambio_Dueño> Cambio_Dueño { get; set; }
        public virtual DbSet<Carros_Remolques_Factura_Declaracion> Carros_Remolques_Factura_Declaracion { get; set; }
        public virtual DbSet<CarrosRemol_Nulos> CarrosRemol_Nulos { get; set; }
        public virtual DbSet<ciudadesMapfre> ciudadesMapfre { get; set; }
        public virtual DbSet<Codigos_ComunaJPL_SRCEI> Codigos_ComunaJPL_SRCEI { get; set; }
        public virtual DbSet<Codigos_JPL_SRCEI> Codigos_JPL_SRCEI { get; set; }
        public virtual DbSet<Compañias_De_Seguros> Compañias_De_Seguros { get; set; }
        public virtual DbSet<Comprobantes_Pago_Multas> Comprobantes_Pago_Multas { get; set; }
        public virtual DbSet<Comunas> Comunas { get; set; }
        public virtual DbSet<comunasConsorcio> comunasConsorcio { get; set; }
        public virtual DbSet<comunasMapfre> comunasMapfre { get; set; }
        public virtual DbSet<Configuracion_Datos_Padron> Configuracion_Datos_Padron { get; set; }
        public virtual DbSet<Configuracion_Posiciones_Padron> Configuracion_Posiciones_Padron { get; set; }
        public virtual DbSet<Configuracion_Sistema> Configuracion_Sistema { get; set; }
        public virtual DbSet<Contaminacion> Contaminacion { get; set; }
        public virtual DbSet<Control_Folios_Internet> Control_Folios_Internet { get; set; }
        public virtual DbSet<Control_Folios_Internet_InHouse> Control_Folios_Internet_InHouse { get; set; }
        public virtual DbSet<Control_Pago_Deuda> Control_Pago_Deuda { get; set; }
        public virtual DbSet<Control_Vencimiento_CHI> Control_Vencimiento_CHI { get; set; }
        public virtual DbSet<Correo_Factura> Correo_Factura { get; set; }
        public virtual DbSet<Correos_por_proceso_masivo> Correos_por_proceso_masivo { get; set; }
        public virtual DbSet<Crea_Correlativo_Varios> Crea_Correlativo_Varios { get; set; }
        public virtual DbSet<Cuentas_por_Periodo> Cuentas_por_Periodo { get; set; }
        public virtual DbSet<Datos_del_CarrosRemolques> Datos_del_CarrosRemolques { get; set; }
        public virtual DbSet<Datos_del_Vehiculo> Datos_del_Vehiculo { get; set; }
        public virtual DbSet<Datos_del_Vehiculo_01> Datos_del_Vehiculo_01 { get; set; }
        public virtual DbSet<Datos_del_Vehiculo_Resp> Datos_del_Vehiculo_Resp { get; set; }
        public virtual DbSet<Datos_Historico_CarrosRemolques> Datos_Historico_CarrosRemolques { get; set; }
        public virtual DbSet<Datos_Incorporacion> Datos_Incorporacion { get; set; }
        public virtual DbSet<DerVar> DerVar { get; set; }
        public virtual DbSet<Detalle_Contaminacion> Detalle_Contaminacion { get; set; }
        public virtual DbSet<Detalle_Derechos_Varios> Detalle_Derechos_Varios { get; set; }
        public virtual DbSet<Detalle_Encuesta_Anual> Detalle_Encuesta_Anual { get; set; }
        public virtual DbSet<Documento_Factura> Documento_Factura { get; set; }
        public virtual DbSet<Documento_Traslado> Documento_Traslado { get; set; }
        public virtual DbSet<Duplicados> Duplicados { get; set; }
        public virtual DbSet<Eliminacion_por_Decreto> Eliminacion_por_Decreto { get; set; }
        public virtual DbSet<EQU_COMUNAS_CONSORCIO> EQU_COMUNAS_CONSORCIO { get; set; }
        public virtual DbSet<Estados_de_Traslados> Estados_de_Traslados { get; set; }
        public virtual DbSet<Ficha_Vehiculo> Ficha_Vehiculo { get; set; }
        public virtual DbSet<firmasContribuyente> firmasContribuyente { get; set; }
        public virtual DbSet<Generacion_Preemision> Generacion_Preemision { get; set; }
        public virtual DbSet<Glosa_Multas_de_Transito> Glosa_Multas_de_Transito { get; set; }
        public virtual DbSet<Hist_Rev_Tecnicas_Seguros> Hist_Rev_Tecnicas_Seguros { get; set; }
        public virtual DbSet<Historico_CorreccionMon> Historico_CorreccionMon { get; set; }
        public virtual DbSet<Historico_Reemplazo_Placas> Historico_Reemplazo_Placas { get; set; }
        public virtual DbSet<Historico_Tasaciones> Historico_Tasaciones { get; set; }
        public virtual DbSet<Huella_Usuario> Huella_Usuario { get; set; }
        public virtual DbSet<Impuesto> Impuesto { get; set; }
        public virtual DbSet<Indices> Indices { get; set; }
        public virtual DbSet<Informe_Dinamico_QR> Informe_Dinamico_QR { get; set; }
        public virtual DbSet<Lugares> Lugares { get; set; }
        public virtual DbSet<Mantenedor_Correos> Mantenedor_Correos { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Mensaje_Correo_Factura> Mensaje_Correo_Factura { get; set; }
        public virtual DbSet<No_Preemitir> No_Preemitir { get; set; }
        public virtual DbSet<Notificacion_Actualizacion_Estructura__> Notificacion_Actualizacion_Estructura__ { get; set; }
        public virtual DbSet<Pago_de_Sellos> Pago_de_Sellos { get; set; }
        public virtual DbSet<Pagos_Adicionales> Pagos_Adicionales { get; set; }
        public virtual DbSet<parametros_fuente> parametros_fuente { get; set; }
        public virtual DbSet<Parametros_Generales> Parametros_Generales { get; set; }
        public virtual DbSet<PASO_PERMISO> PASO_PERMISO { get; set; }
        public virtual DbSet<Periodos> Periodos { get; set; }
        public virtual DbSet<Permisos_00> Permisos_00 { get; set; }
        public virtual DbSet<Permisos_de_Circulacion> Permisos_de_Circulacion { get; set; }
        public virtual DbSet<Permisos_Resp> Permisos_Resp { get; set; }
        public virtual DbSet<Permisos_Robados> Permisos_Robados { get; set; }
        public virtual DbSet<Posiciones_Primer_Cuerpo> Posiciones_Primer_Cuerpo { get; set; }
        public virtual DbSet<Posiciones_Segundo_Cuerpo> Posiciones_Segundo_Cuerpo { get; set; }
        public virtual DbSet<Prescripcion_Adjuntos> Prescripcion_Adjuntos { get; set; }
        public virtual DbSet<PROP_1> PROP_1 { get; set; }
        public virtual DbSet<Propietarios> Propietarios { get; set; }
        public virtual DbSet<Propietarios_0> Propietarios_0 { get; set; }
        public virtual DbSet<Rebaja_de_Multas> Rebaja_de_Multas { get; set; }
        public virtual DbSet<Reg_Rev_Tecnicas_Robadas> Reg_Rev_Tecnicas_Robadas { get; set; }
        public virtual DbSet<Reg_Sellos_Robados> Reg_Sellos_Robados { get; set; }
        public virtual DbSet<regionesMapfre> regionesMapfre { get; set; }
        public virtual DbSet<Registro_Automotoras_Internet> Registro_Automotoras_Internet { get; set; }
        public virtual DbSet<Registro_de_Multas> Registro_de_Multas { get; set; }
        public virtual DbSet<Registro_de_multas_de_paso> Registro_de_multas_de_paso { get; set; }
        public virtual DbSet<Registro_de_Multas_Pagadas> Registro_de_Multas_Pagadas { get; set; }
        public virtual DbSet<Registro_de_Multas_Pagadas_Convenio> Registro_de_Multas_Pagadas_Convenio { get; set; }
        public virtual DbSet<Registro_de_Multas_PagadasOtrasComunas> Registro_de_Multas_PagadasOtrasComunas { get; set; }
        public virtual DbSet<Registro_de_multas_Prescritas> Registro_de_multas_Prescritas { get; set; }
        public virtual DbSet<Registro_de_Preemisiones> Registro_de_Preemisiones { get; set; }
        public virtual DbSet<RegistroLinkDuplicados> RegistroLinkDuplicados { get; set; }
        public virtual DbSet<Registros_por_cargas_masivas> Registros_por_cargas_masivas { get; set; }
        public virtual DbSet<Renovacion_Adjuntos> Renovacion_Adjuntos { get; set; }
        public virtual DbSet<Respaldo_SII> Respaldo_SII { get; set; }
        public virtual DbSet<Respaldo_Version> Respaldo_Version { get; set; }
        public virtual DbSet<Resultado_Pagos_Adicionales> Resultado_Pagos_Adicionales { get; set; }
        public virtual DbSet<Sellos> Sellos { get; set; }
        public virtual DbSet<Sellos_Nulos> Sellos_Nulos { get; set; }
        public virtual DbSet<Sellos_Placas> Sellos_Placas { get; set; }
        public virtual DbSet<Sellos_Vehiculo> Sellos_Vehiculo { get; set; }
        public virtual DbSet<SII> SII { get; set; }
        public virtual DbSet<SII_Paso> SII_Paso { get; set; }
        public virtual DbSet<Solicitud_de_Traslado> Solicitud_de_Traslado { get; set; }
        public virtual DbSet<TIPOS_DE_CARROCERIAS> TIPOS_DE_CARROCERIAS { get; set; }
        public virtual DbSet<Tipos_de_Documentos> Tipos_de_Documentos { get; set; }
        public virtual DbSet<Tipos_de_Ingreso> Tipos_de_Ingreso { get; set; }
        public virtual DbSet<Tipos_de_Pago> Tipos_de_Pago { get; set; }
        public virtual DbSet<Tipos_de_Vehiculos> Tipos_de_Vehiculos { get; set; }
        public virtual DbSet<Tipos_de_Vehiculos_BCI> Tipos_de_Vehiculos_BCI { get; set; }
        public virtual DbSet<Tipos_de_Vehiculos_EquivalenciasSeguro> Tipos_de_Vehiculos_EquivalenciasSeguro { get; set; }
        public virtual DbSet<Tipos_de_Vehiculos_Seguro> Tipos_de_Vehiculos_Seguro { get; set; }
        public virtual DbSet<Tipos_Monedas> Tipos_Monedas { get; set; }
        public virtual DbSet<Totales_Morosos> Totales_Morosos { get; set; }
        public virtual DbSet<Transacciones_AACH> Transacciones_AACH { get; set; }
        public virtual DbSet<Transacciones_Aseguradoras> Transacciones_Aseguradoras { get; set; }
        public virtual DbSet<Transacciones_BcoChile> Transacciones_BcoChile { get; set; }
        public virtual DbSet<Transacciones_BcoChile_Detalle> Transacciones_BcoChile_Detalle { get; set; }
        public virtual DbSet<Transacciones_Consorcio> Transacciones_Consorcio { get; set; }
        public virtual DbSet<Transacciones_ImpExp> Transacciones_ImpExp { get; set; }
        public virtual DbSet<Transacciones_Mapfre> Transacciones_Mapfre { get; set; }
        public virtual DbSet<Transacciones_Mapfre_v1> Transacciones_Mapfre_v1 { get; set; }
        public virtual DbSet<Transacciones_MTT> Transacciones_MTT { get; set; }
        public virtual DbSet<Transacciones_Registro_Civil> Transacciones_Registro_Civil { get; set; }
        public virtual DbSet<Transacciones_TesoreriaGeneral> Transacciones_TesoreriaGeneral { get; set; }
        public virtual DbSet<Transacciones_TesoreriaGeneral_Detalle> Transacciones_TesoreriaGeneral_Detalle { get; set; }
        public virtual DbSet<Transacciones_Transbank> Transacciones_Transbank { get; set; }
        public virtual DbSet<Transacciones_Transbank_Detalle> Transacciones_Transbank_Detalle { get; set; }
        public virtual DbSet<Transacciones_Transbank_Pago_Automatico> Transacciones_Transbank_Pago_Automatico { get; set; }
        public virtual DbSet<Traslados_de_Vehiculos___> Traslados_de_Vehiculos___ { get; set; }
        public virtual DbSet<Traslados_Internet> Traslados_Internet { get; set; }
        public virtual DbSet<Traslados_Resp> Traslados_Resp { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Usuarios_Externos> Usuarios_Externos { get; set; }
        public virtual DbSet<Valores_Monedas> Valores_Monedas { get; set; }
        public virtual DbSet<Vehiculos_Fuera_Circulacion> Vehiculos_Fuera_Circulacion { get; set; }
        public virtual DbSet<Verificacion_Ingreso> Verificacion_Ingreso { get; set; }
    }
}
