//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion_Actualizacion_Estructura__
    {
        public int ID { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Descripcion { get; set; }
        public string Sentencia { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
