//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago_de_Sellos
    {
        public string Placa { get; set; }
        public string Numero_Sello { get; set; }
        public System.DateTime Fecha_Pago { get; set; }
        public int Monto_Pago { get; set; }
        public string Folio_Ingreso { get; set; }
    }
}
