//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos_Adicionales
    {
        public string Tipo_pago { get; set; }
        public int Cod_pago { get; set; }
        public string Glosa { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<int> Cod_Item { get; set; }
        public string Departamento { get; set; }
        public string Item { get; set; }
        public Nullable<int> Item_Pago { get; set; }
        public Nullable<bool> Existe { get; set; }
        public Nullable<bool> Tipo_Cobro { get; set; }
    }
}
