//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametros_fuente
    {
        public int Tamaño_letra { get; set; }
        public string Tipo_de_fuente { get; set; }
        public string Estilo_fuente { get; set; }
        public Nullable<int> Tamaño_Hoja { get; set; }
        public Nullable<int> Ancho_Hoja { get; set; }
        public Nullable<int> Alto_Hoja { get; set; }
    }
}
