//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_Generales
    {
        public bool Correccion_Monetaria { get; set; }
        public Nullable<float> Correccion_Marzo { get; set; }
        public Nullable<float> Correccion_Mayo { get; set; }
        public Nullable<float> Correccion_Septiembre { get; set; }
        public bool Desglosar_Fondo_Comun { get; set; }
        public string Glosa_FdoComun { get; set; }
        public string Glosa_FdoMunicipal { get; set; }
        public bool Totalizar_Boletin { get; set; }
        public Nullable<float> Porcentaje_Duplicado { get; set; }
        public Nullable<short> Fecha_Referencia { get; set; }
        public bool Enlace_Tesoreria { get; set; }
        public Nullable<short> Codigo_Departamento { get; set; }
        public bool Registro_de_Sellos { get; set; }
        public bool Eliminar_por_Decreto { get; set; }
        public bool Guardar_CiaSeguros { get; set; }
        public bool Guardar_RevTecnica { get; set; }
        public bool Guardar_NroMotor { get; set; }
        public Nullable<short> Tesoreria_Clipper { get; set; }
        public Nullable<short> Cuentas_por_Periodo { get; set; }
        public Nullable<short> Minimo_Factura { get; set; }
        public Nullable<short> Correlativo_Unico { get; set; }
        public Nullable<short> Codigo_Departamento_Derechos_Varios { get; set; }
        public bool Convenio_Pagos { get; set; }
        public bool Transferencias { get; set; }
        public Nullable<double> Valor_Transferencia { get; set; }
        public Nullable<int> Porcentaje_Transferencia { get; set; }
        public Nullable<int> Largo_NroBoletin { get; set; }
        public double NroBoletinAutomatico { get; set; }
        public short Bloqueo_Modificaciones { get; set; }
        public Nullable<short> Val_Rango_Boletines { get; set; }
        public Nullable<short> Rango_Sellos { get; set; }
        public Nullable<short> Revisiones_Tecnicas_Robadas { get; set; }
        public Nullable<short> Numero_Orden_Registro_Multa { get; set; }
        public Nullable<short> Repite_Boletin { get; set; }
        public Nullable<short> ValidaPagoAnterior { get; set; }
        public string Glosa_ZonaFranca { get; set; }
        public Nullable<int> Ver_NBoletin { get; set; }
        public Nullable<int> Imprimir_Boletin { get; set; }
        public Nullable<int> Interes_Factura { get; set; }
        public Nullable<bool> Valida_Fono_Fijo { get; set; }
        public Nullable<bool> Valida_Movil { get; set; }
        public Nullable<bool> Clasificador_Presupuestario2008 { get; set; }
        public Nullable<bool> Emitir_Multas { get; set; }
        public Nullable<short> Conectar_WebService { get; set; }
        public string WebService { get; set; }
        public string WSDL_WebService { get; set; }
        public string Usuario_WebService { get; set; }
        public string Contraseña_WebService { get; set; }
        public Nullable<short> Lee_WebService_Auto { get; set; }
        public Nullable<bool> Vista_Tasaciones { get; set; }
        public Nullable<bool> Conexion_Net { get; set; }
        public Nullable<int> Codigo_Cliente { get; set; }
        public string Ruta_Wsdl { get; set; }
        public Nullable<bool> Habilita_F7 { get; set; }
        public Nullable<bool> ConvierteUTMaPesos { get; set; }
        public Nullable<int> Act_Numero_Boletin_Preimpreso { get; set; }
        public Nullable<int> Envio_Correos { get; set; }
        public string Direccion_Correo { get; set; }
        public string Direccion_Host { get; set; }
        public string Logo_Ruta { get; set; }
        public Nullable<bool> traslados_automaticos { get; set; }
        public Nullable<bool> Forma_de_Trabajo { get; set; }
        public string Dir_Logo { get; set; }
        public Nullable<bool> Conexion_Registro_Civil { get; set; }
        public string Ruta_Conexion_Registro_Civil { get; set; }
        public string Validacion_Cajas { get; set; }
        public Nullable<bool> Conexion_MTT { get; set; }
        public string Usuario_MTT { get; set; }
        public string Clave_MTT { get; set; }
        public string Ruta_Conexion_MTT { get; set; }
        public string Ruta_Wsdl_Ecom { get; set; }
        public Nullable<bool> Activa_impresion_boletin { get; set; }
        public Nullable<bool> activa_impresion_dinamica { get; set; }
        public string Ruta_ImagenesEcom { get; set; }
        public string Ruta_WSDLEmail { get; set; }
        public Nullable<short> VPrimera_Cuota { get; set; }
        public Nullable<short> VSegunda_Cuota { get; set; }
        public string Password { get; set; }
        public string ServidorPop3 { get; set; }
        public string NombreEmisor { get; set; }
        public string CorreoEmisor { get; set; }
        public string Asunto { get; set; }
        public string ServidorSmtp { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public string ConmentarioAdicional { get; set; }
        public Nullable<int> Puerto_SMTP { get; set; }
        public string Mail_Autentificacion { get; set; }
        public string Mail_Autentificacion_TLS { get; set; }
        public string Ruta_Renovacion { get; set; }
        public Nullable<int> ECOM_Conectado { get; set; }
        public string ECOM_URL_WS { get; set; }
        public Nullable<int> ECOM_Codigo_Cliente { get; set; }
        public int Pago_Automatico_Ecom { get; set; }
        public string Registro_Multas_WS { get; set; }
        public string Ruta_Vecino_Digital { get; set; }
        public string DirHuellas { get; set; }
        public string Conexion_Soap { get; set; }
        public string Usuario_SOAP { get; set; }
        public string Clave_SOAP { get; set; }
        public string VD_URL_WS_Traslados { get; set; }
        public Nullable<bool> Valida_Email { get; set; }
        public Nullable<int> Vehiculo_Factura { get; set; }
        public Nullable<bool> Conexion_RPI { get; set; }
        public string Ruta_RPI { get; set; }
        public string Usuario_RPI { get; set; }
        public string Clave_RPI { get; set; }
        public string link_servicios_Genera_Masivos { get; set; }
        public string Credenciales_Servicios_Masivos { get; set; }
        public Nullable<int> Cantidad_masivos { get; set; }
        public Nullable<int> Codigo_Municipalidad { get; set; }
        public Nullable<bool> Formato_Casa_Moneda { get; set; }
        public short Activa_Convenio { get; set; }
        public Nullable<bool> FirmaElectronica_Activar { get; set; }
        public string FirmaElectronica_Repositorio { get; set; }
        public string FirmaElectronica_UsuarioDirector { get; set; }
        public Nullable<bool> FirmaElectronica_ActivaFirmaContribuyente { get; set; }
        public string FirmaElectronica_RepositorioFirmas { get; set; }
        public string FirmaElectronica_RutaDirector { get; set; }
        public short Activa_MultasTag { get; set; }
        public string FechaLimite_UnaCuota { get; set; }
        public string FechaLimite_Convenio { get; set; }
        public Nullable<int> Cobro_2020 { get; set; }
        public Nullable<int> ActivarSerializacion { get; set; }
    }
}
