//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASO_PERMISO
    {
        public string PLACA { get; set; }
        public string RUT { get; set; }
        public short AÑO_DEL_PERMISO { get; set; }
        public string Forma_de_pago { get; set; }
    }
}
