//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodos
    {
        public short Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha_Renovacion { get; set; }
        public Nullable<System.DateTime> Fecha_VencCtdo { get; set; }
        public Nullable<System.DateTime> Fecha_Venc1raCta { get; set; }
        public Nullable<short> UTM_Mes { get; set; }
        public Nullable<short> UTM_Mes_Factura { get; set; }
        public Nullable<bool> Limite_Traslado { get; set; }
        public Nullable<System.DateTime> Fecha_Limite_Traslado { get; set; }
        public Nullable<bool> Periodo_Prueba { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio_Segunda_Cuota { get; set; }
        public Nullable<short> UTM_CalculoIPC { get; set; }
    }
}
