//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos_00
    {
        public string Placa { get; set; }
        public string Digito { get; set; }
        public string Rut { get; set; }
        public short Año_del_Permiso { get; set; }
        public Nullable<System.DateTime> Fecha_Emision { get; set; }
        public short Tipo_Vehiculo { get; set; }
        public Nullable<short> Periodo { get; set; }
        public Nullable<short> Clasificacion { get; set; }
        public Nullable<double> Tasacion { get; set; }
        public Nullable<int> Neto_Factura { get; set; }
        public Nullable<System.DateTime> Fecha_Factura { get; set; }
        public Nullable<double> Valor_UTM { get; set; }
        public Nullable<short> Comuna_Anterior { get; set; }
        public Nullable<short> Año_Anterior { get; set; }
        public Nullable<short> Compañia_Seguro { get; set; }
        public string Numero_Poliza { get; set; }
        public string Nro_Revision_Tecnica { get; set; }
        public string Lugar_Revision_Tecnica { get; set; }
        public string Folio_Gases { get; set; }
        public short Forma_de_Pago { get; set; }
        public Nullable<double> Numero_Boletin { get; set; }
        public Nullable<int> Numero_Caja { get; set; }
        public Nullable<int> Valor_Permiso { get; set; }
        public Nullable<float> Porcentaje_IPC { get; set; }
        public Nullable<float> Porcentaje_Multa { get; set; }
        public Nullable<int> Valor_IPC { get; set; }
        public Nullable<int> Valor_Multa { get; set; }
        public Nullable<int> Total_a_Pagar { get; set; }
        public Nullable<short> Estado_del_Pago { get; set; }
        public bool Fondos_a_Terceros { get; set; }
        public Nullable<int> Valor_Contado { get; set; }
        public Nullable<int> Valor_Cuota { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento { get; set; }
        public string Observaciones { get; set; }
        public bool Correccion_Monetaria { get; set; }
        public Nullable<float> Porcentaje_Correccion { get; set; }
        public Nullable<int> Monto_Correccion { get; set; }
        public Nullable<byte> Origen { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
        public Nullable<short> Comuna_Origen { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> Correlativo_Caja { get; set; }
        public string Usuario_Caja { get; set; }
        public Nullable<short> Año_Proceso { get; set; }
        public Nullable<double> Valor_Permiso_FondoC { get; set; }
        public Nullable<double> Valor_Permiso_FondoM { get; set; }
        public Nullable<double> Valor_Ipc_FondoC { get; set; }
        public Nullable<double> Valor_Ipc_FondoM { get; set; }
        public Nullable<double> Valor_CMonetaria_FondoC { get; set; }
        public Nullable<double> Valor_CMonetaria_FondoM { get; set; }
        public Nullable<int> Codigo_Empresa_Procedencia { get; set; }
        public Nullable<float> Numero_Boletin_Preimpreso { get; set; }
        public string Municipalidad { get; set; }
        public string Derechos_Varios { get; set; }
        public string Id_Multas { get; set; }
        public Nullable<double> Monto_RNMT { get; set; }
        public Nullable<int> Cantidad_RNMT { get; set; }
        public string SeriesQR { get; set; }
        public string Rut_X { get; set; }
    }
}
