//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posiciones_Segundo_Cuerpo
    {
        public int Codigo { get; set; }
        public string Campo { get; set; }
        public int Posicion_y { get; set; }
        public int Posicion_X { get; set; }
        public string Tabla { get; set; }
    }
}
