//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescripcion_Adjuntos
    {
        public string Placa_Adjuntos { get; set; }
        public double ID_Multa { get; set; }
        public string Archivo { get; set; }
        public byte[] Doc_Digital { get; set; }
    }
}
