//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROP_1
    {
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Comuna { get; set; }
        public string Ciudad { get; set; }
        public string Telefono { get; set; }
        public string Codigo_Postal { get; set; }
        public Nullable<int> Codigo_Empresa { get; set; }
        public string Mail { get; set; }
        public string Telefono_Movil { get; set; }
        public string RUT_X { get; set; }
    }
}
