//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registros_por_cargas_masivas
    {
        public decimal Id_Archivo { get; set; }
        public string Placa { get; set; }
        public string Fecha_Archivo { get; set; }
        public decimal Numero_Boletin { get; set; }
        public int Año_Permiso { get; set; }
        public int Forma_de_Pago { get; set; }
        public int Estado { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fecha_Carga { get; set; }
        public string Equipo { get; set; }
        public string Nombre_Archivo { get; set; }
        public Nullable<decimal> Registros_por_Archivo { get; set; }
        public string Link_Permiso { get; set; }
        public string Empresa { get; set; }
        public int Valor_Permiso { get; set; }
    }
}
