//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_Automotoras_Internet
    {
        public short Codigo_Municipalidad { get; set; }
        public short Codigo_Automotora { get; set; }
        public string Descripcion { get; set; }
        public string Rut { get; set; }
        public string Clave_Acceso { get; set; }
    }
}
