//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroLinkDuplicados
    {
        public int Id { get; set; }
        public string Placa { get; set; }
        public Nullable<short> Forma_de_Pago { get; set; }
        public Nullable<short> Año_del_Permiso { get; set; }
        public Nullable<double> Numero_Boletin { get; set; }
        public Nullable<System.DateTime> Fecha_Emision { get; set; }
        public Nullable<int> Valor_Duplicado { get; set; }
        public string Link_Duplicado { get; set; }
    }
}
