//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_de_Preemisiones
    {
        public short Año { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Placa { get; set; }
        public Nullable<double> Numero_Boletin { get; set; }
        public Nullable<int> Valor_Contado { get; set; }
        public Nullable<int> Valor_Cuota { get; set; }
        public Nullable<double> Valor_IPC { get; set; }
        public short Tipo { get; set; }
        public Nullable<double> Numero_Caja { get; set; }
        public Nullable<double> Numero_Boletin_Caja { get; set; }
        public Nullable<System.DateTime> Fecha_Pago_Caja { get; set; }
        public string ID_Usuario { get; set; }
        public Nullable<int> Estado_del_Permiso { get; set; }
        public Nullable<short> Clasificacion { get; set; }
        public Nullable<double> Tasacion { get; set; }
        public Nullable<double> Valor_UTM { get; set; }
        public Nullable<short> Comuna_Anterior { get; set; }
        public Nullable<short> Ano_Anterior { get; set; }
        public Nullable<short> Correccion_Monetaria { get; set; }
        public Nullable<double> Monto_Correccion { get; set; }
        public Nullable<int> Numero_Caja_Transito { get; set; }
        public Nullable<System.DateTime> Fecha_Anulacion { get; set; }
        public string Glosa_Anulacion { get; set; }
        public string Tipo_Vehiculo { get; set; }
        public string Periodo { get; set; }
        public string Rut_Propietario { get; set; }
    }
}
