//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado_Pagos_Adicionales
    {
        public decimal ID_Pagos { get; set; }
        public string Placa { get; set; }
        public Nullable<decimal> Numero_Boletin { get; set; }
        public Nullable<decimal> Año_del_Permiso { get; set; }
        public string Descripcion_Pago { get; set; }
        public Nullable<decimal> Monto { get; set; }
    }
}
