//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sellos
    {
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Glosa { get; set; }
        public string DesdeSello { get; set; }
        public string HastaSello { get; set; }
        public string Usuario_Sello { get; set; }
    }
}
