//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sellos_Placas
    {
        public string Placa { get; set; }
        public decimal Orden_de_Ingreso { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public int N_Sello { get; set; }
        public Nullable<int> Monto { get; set; }
        public string Glosa { get; set; }
    }
}
