//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sellos_Vehiculo
    {
        public string Placa { get; set; }
        public int Tipo_Sello { get; set; }
        public string Numero_Sello { get; set; }
        public Nullable<System.DateTime> Fecha_Entrega { get; set; }
        public string Observacion { get; set; }
    }
}
