//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class SII
    {
        public string Codigo { get; set; }
        public string Tipo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Pais { get; set; }
        public Nullable<byte> Numero_de_Puertas { get; set; }
        public Nullable<short> Cilindrada { get; set; }
        public string Combustible { get; set; }
        public string Transmision { get; set; }
        public string Equipamiento { get; set; }
        public Nullable<double> Tasacion { get; set; }
        public Nullable<short> Año_Fabricacion { get; set; }
        public Nullable<short> Tasaciones_del_Año { get; set; }
        public string Codigo_Antiguo { get; set; }
        public string Potencia { get; set; }
        public string Marchas { get; set; }
        public string Traccion { get; set; }
        public string Equipamiento_Detallado { get; set; }
        public Nullable<double> Permiso_Año { get; set; }
        public string Version { get; set; }
    }
}
