//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class SII_Paso
    {
        public string Codigo { get; set; }
        public string Tipo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Pais { get; set; }
        public string Numero_de_Puertas { get; set; }
        public string Cilindrada { get; set; }
        public string Combustible { get; set; }
        public string Transmision { get; set; }
        public string Equipamiento { get; set; }
        public string Tasacion { get; set; }
        public string Año_Fabricacion { get; set; }
        public string Tasaciones_del_Año { get; set; }
    }
}
