//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_de_Traslado
    {
        public Nullable<short> Codigo_Comuna { get; set; }
        public string Placa { get; set; }
        public Nullable<System.DateTime> Fecha_Solicitud { get; set; }
        public bool Imprimir { get; set; }
        public string Tip_Trasla { get; set; }
    }
}
