//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos_de_Vehiculos
    {
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<short> Periodo { get; set; }
        public Nullable<double> UTM { get; set; }
        public Nullable<int> Tonelaje_Inicial1 { get; set; }
        public Nullable<int> Tonelaje_Final1 { get; set; }
        public Nullable<double> UTM_1 { get; set; }
        public Nullable<int> Tonelaje_Inicial2 { get; set; }
        public Nullable<int> Tonelaje_Final2 { get; set; }
        public Nullable<double> UTM_2 { get; set; }
        public Nullable<int> Tonelaje_Inicial3 { get; set; }
        public Nullable<int> Tonelaje_Final3 { get; set; }
        public Nullable<double> UTM_3 { get; set; }
        public Nullable<int> Tonelaje_Inicial4 { get; set; }
        public Nullable<int> Tonelaje_Final4 { get; set; }
        public Nullable<double> UTM_4 { get; set; }
        public string Mascara_Placa { get; set; }
        public Nullable<short> Tipo_Calculo { get; set; }
        public Nullable<short> Vida_Util { get; set; }
        public Nullable<short> Exigir_Sello { get; set; }
        public Nullable<short> Vida_util_Taxi_Colectivo { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento { get; set; }
        public Nullable<short> Bloqueado_para_PagosWEB { get; set; }
    }
}
