//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos_de_Vehiculos_Seguro
    {
        public short Codigo_CiaSeguro { get; set; }
        public short Codigo_Tipo_Vehiculo { get; set; }
        public string Descripcion { get; set; }
        public int Valor_Seguro { get; set; }
        public Nullable<short> Periodo { get; set; }
        public Nullable<int> Valor_Seguro_Bco { get; set; }
    }
}
