//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Totales_Morosos
    {
        public short Mes { get; set; }
        public short Año { get; set; }
        public Nullable<int> Total_1 { get; set; }
        public Nullable<int> Total_2 { get; set; }
        public Nullable<int> Total_3 { get; set; }
        public Nullable<int> Total_4 { get; set; }
        public Nullable<int> Total_5 { get; set; }
        public Nullable<int> Total_6 { get; set; }
        public Nullable<int> Total_7 { get; set; }
    }
}
