//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones_Registro_Civil
    {
        public decimal Codigo { get; set; }
        public string Placa { get; set; }
        public string Consulta { get; set; }
        public string Respuesta { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
