//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones_Transbank_Pago_Automatico
    {
        public int Id_Transacciones_Transbank_Pago_Automatico { get; set; }
        public string Tbk_Orden_Compra { get; set; }
        public Nullable<int> Codigo_Area { get; set; }
        public Nullable<int> Item_Pago { get; set; }
        public Nullable<int> Orden_Ingreso { get; set; }
        public string Fecha_Pago { get; set; }
        public Nullable<int> Ano_Permiso { get; set; }
        public Nullable<int> Forma_Pago_Permiso { get; set; }
        public string Identificador_Transaccion { get; set; }
        public string Cod_Auto_Transaccion { get; set; }
        public string OrdenSubDetalle { get; set; }
        public Nullable<int> CodigoMunicipalidad { get; set; }
        public Nullable<int> Id_Multa { get; set; }
    }
}
