//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones_Consorcio
    {
        public long nroTransaccion { get; set; }
        public string idCompra { get; set; }
        public string idConvenio { get; set; }
        public string rutPagador { get; set; }
        public string dvRutPagador { get; set; }
        public string nombrePagador { get; set; }
        public string apellidoPaternoPagador { get; set; }
        public string apellidoMaternoPagador { get; set; }
        public string emailPagador { get; set; }
        public string patente { get; set; }
        public string tipoVehiculo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string anno { get; set; }
        public string nroMotor { get; set; }
        public string rutPropietario { get; set; }
        public string dvRutPropietario { get; set; }
        public string nombrePropietario { get; set; }
        public string apellidoPaternoPropietario { get; set; }
        public string apellidoMaternoPropietario { get; set; }
        public string direccionDespacho { get; set; }
        public string comuna { get; set; }
        public string region { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string monto { get; set; }
        public string idCarro { get; set; }
        public string idItem { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string nroPoliza { get; set; }
        public string url { get; set; }
    }
}
