//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones_BcoChile
    {
        public int id { get; set; }
        public string Placa { get; set; }
        public System.DateTime Fecha { get; set; }
        public int idpedido { get; set; }
        public string idcom { get; set; }
        public string idtrx { get; set; }
        public int total { get; set; }
        public short nropagos { get; set; }
        public short estado { get; set; }
        public Nullable<int> codret { get; set; }
        public string descret { get; set; }
        public string fechatrx { get; set; }
        public Nullable<int> fechacont { get; set; }
        public string numcomp { get; set; }
        public string RT_RazonSocial { get; set; }
        public string RT_NumeroCertificado { get; set; }
        public string CS_CiaSeguro { get; set; }
        public string CS_NumeroPoliza { get; set; }
        public string CS_ValorSeguro { get; set; }
        public string DL_NombreContacto { get; set; }
        public string DL_DireccionContacto { get; set; }
        public string DL_TelefonoContacto { get; set; }
        public string DL_DiasVisita { get; set; }
        public string DL_HorasVisita { get; set; }
        public string DL_MailContacto { get; set; }
        public string HOMOLOGADO { get; set; }
        public string REVTEC_WS_MTT { get; set; }
        public string SEGURO_ONLINE_WS_AACH { get; set; }
        public string COMPRA_SEGURO_ONLINE { get; set; }
    }
}
