//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones_BcoChile_Detalle
    {
        public int id { get; set; }
        public int srvrec { get; set; }
        public int monto { get; set; }
        public string glosa { get; set; }
        public short cantidad { get; set; }
        public int precio { get; set; }
        public string datoadic { get; set; }
        public string xmllog { get; set; }
    }
}
