//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones_AACH
    {
        public int id { get; set; }
        public string CodError { get; set; }
        public string Error { get; set; }
        public Nullable<int> Ticket { get; set; }
        public string NroFolio { get; set; }
        public string NroPoliza { get; set; }
        public string RutCia { get; set; }
        public string NombreCompania { get; set; }
        public string Patente { get; set; }
        public string DigPatene { get; set; }
        public string TipoVehiculo { get; set; }
        public string MarcaVehiculo { get; set; }
        public string ModeloVehiculo { get; set; }
        public string Anofabricacion { get; set; }
        public string NroMotor { get; set; }
        public string RutPropietario { get; set; }
        public string NombrePropietario { get; set; }
        public string FechaInicio { get; set; }
        public string fechaTermino { get; set; }
    }
}
