//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones_Aseguradoras
    {
        public int id { get; set; }
        public string idCompra { get; set; }
        public string patente { get; set; }
        public Nullable<int> cod_aseg { get; set; }
        public string url { get; set; }
        public string nroPoliza { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> nroTransaccionAseg { get; set; }
        public string envioPoliza { get; set; }
    }
}
