//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones_Mapfre_v1
    {
        public long nroTransaccion { get; set; }
        public string idCompra { get; set; }
        public string patente { get; set; }
        public string tipoVehiculo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string anno { get; set; }
        public string nroMotor { get; set; }
        public string rutPropietario { get; set; }
        public string dvRutPropietario { get; set; }
        public string nombrePropietario { get; set; }
        public string monto_mapfre { get; set; }
        public string monto_cas { get; set; }
        public string monto_total { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string nroPoliza { get; set; }
        public string url { get; set; }
        public string codMuni { get; set; }
        public string num_mensaje { get; set; }
        public string desc_mensaje { get; set; }
        public string envio_seguro { get; set; }
        public string pagado { get; set; }
    }
}
