//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones_MTT
    {
        public int id { get; set; }
        public string Placa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string COD_RESULTADO { get; set; }
        public string RESULTADO { get; set; }
        public Nullable<short> estadorevtec { get; set; }
        public string COMUNA_PRT { get; set; }
        public string CODIGO_PRT { get; set; }
        public string ID_CRT { get; set; }
        public byte[] MARCA { get; set; }
        public string MODELO { get; set; }
        public string NUMERO_CHASIS { get; set; }
        public string TIPO_COMBUSTIBLE { get; set; }
        public string TIPO_SELLO { get; set; }
        public string TIPO_VEHICULO { get; set; }
        public string NUMERO_MOTOR { get; set; }
        public string COMUNA_PRT_G { get; set; }
        public string CODIGO_PRT_G { get; set; }
        public string ID_CRT_G { get; set; }
        public string PPUDV { get; set; }
        public string ANO_FABRICACION { get; set; }
        public Nullable<System.DateTime> FECHA_REVISION { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
    }
}
