//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traslados_Internet
    {
        public int int_cod { get; set; }
        public string txt_placa { get; set; }
        public string txt_digito { get; set; }
        public int int_anio_permiso { get; set; }
        public string txt_tipo_vehiculo { get; set; }
        public string txt_marca { get; set; }
        public string txt_modelo { get; set; }
        public int int_anio_fabricacion { get; set; }
        public string txt_color { get; set; }
        public string txt_num_motor { get; set; }
        public string txt_num_chassis { get; set; }
        public Nullable<int> int_num_puertas { get; set; }
        public Nullable<int> int_num_asientos { get; set; }
        public Nullable<int> int_cilindrada { get; set; }
        public string txt_combustible { get; set; }
        public string txt_trasmision { get; set; }
        public string txt_equipamiento { get; set; }
        public string txt_codigo_sii { get; set; }
        public string txt_rut_propietario { get; set; }
        public string txt_razon_social { get; set; }
        public string txt_direccion_propietario { get; set; }
        public string txt_comuna_propietario { get; set; }
        public string txt_telefono_propietario { get; set; }
        public string txt_mail_propietario { get; set; }
        public string txt_municipio { get; set; }
        public double float_folio { get; set; }
        public int int_anio_termino { get; set; }
        public int int_estado { get; set; }
        public int int_estado_notificacion { get; set; }
        public Nullable<System.DateTime> date_fsolicitud { get; set; }
        public Nullable<System.DateTime> date_frecepcion { get; set; }
        public Nullable<System.DateTime> date_faprobacion { get; set; }
        public Nullable<int> int_tasacion { get; set; }
        public Nullable<int> int_ID_SOLICITUD { get; set; }
        public string txt_MAIL_SESION { get; set; }
    }
}
