//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string Nombre_Usuario { get; set; }
        public string Descripcion_Usuario { get; set; }
        public string Clave_de_Acceso { get; set; }
        public Nullable<double> Numero_de_Folio { get; set; }
        public bool Pago_de_Permisos { get; set; }
        public bool Preemision { get; set; }
        public bool Consulta_Cuenta_Corriente { get; set; }
        public bool Traslados_de_Vehiculos { get; set; }
        public bool Tabla_Municipalidad { get; set; }
        public bool Tabla_Marcas { get; set; }
        public bool Tabla_Períodos { get; set; }
        public bool Tabla_Propietarios { get; set; }
        public bool Tabla_Sellos { get; set; }
        public bool Tabla_Seguros { get; set; }
        public bool Tabla_SII { get; set; }
        public bool Tabla_Tipo_Pago { get; set; }
        public bool Tabla_Tipo_Vehiculo { get; set; }
        public bool Tabla_UTM__IPC__Multas { get; set; }
        public bool Tabla_Cajas { get; set; }
        public bool Tabla_Usuarios { get; set; }
        public bool Estadistica_Anexo_I { get; set; }
        public bool Estadistica_Anexo_II_VII { get; set; }
        public bool List_de_Pagos { get; set; }
        public bool List_de_Morosidades_por_Año { get; set; }
        public bool List_RCVM_de_Vehiculos { get; set; }
        public bool List_de_Permisos_por_Año { get; set; }
        public bool List_de_Perm_no_Renovados { get; set; }
        public bool List_de_Perm_Renovados_en_la_Comuna { get; set; }
        public bool List_de_Perm_Renovados_Otras_Comunas { get; set; }
        public bool Adm_de_Cartas { get; set; }
        public bool Centralizacion { get; set; }
    }
}
