//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valores_Monedas
    {
        public short Codigo_Moneda { get; set; }
        public System.DateTime Fecha_Cambio { get; set; }
        public Nullable<double> Valor { get; set; }
    }
}
