//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos_Fuera_Circulacion
    {
        public string Placa { get; set; }
        public Nullable<short> Año_del_Permiso { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<short> Forma_de_Pago { get; set; }
        public Nullable<double> Numero_Registro { get; set; }
    }
}
