//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subdere
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verificacion_Ingreso
    {
        public int Tipo_Vehiculo { get; set; }
        public Nullable<int> Compañia_Seguros { get; set; }
        public Nullable<int> Revision_Tecnica { get; set; }
        public Nullable<int> Rev_Tecnica_Robada { get; set; }
        public Nullable<int> Nro_Motor { get; set; }
        public Nullable<int> Cilindrada { get; set; }
        public Nullable<int> Combustible { get; set; }
        public Nullable<int> Transmision { get; set; }
        public Nullable<int> Equipamiento { get; set; }
        public Nullable<int> Tipo_Sello { get; set; }
        public Nullable<int> Puertas { get; set; }
        public Nullable<int> Numero_Asientos { get; set; }
        public Nullable<int> Numero_Ejes { get; set; }
        public Nullable<int> Numero_Ruedas { get; set; }
        public Nullable<int> valida_tonelaje { get; set; }
        public Nullable<int> Numero_Chasis { get; set; }
    }
}
